name: Update

on:
  workflow_dispatch: {}
  schedule:
    - cron: "22 11 * * *"

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: DeterminateSystems/nix-installer-action@786fff0690178f1234e4e1fe9b536e94f5433196 # v20

      - run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - run: nix flake update --commit-lock-file
      - id: nix-flake-changelog
        run: |
          delimiter="$(openssl rand -hex 16)"
          echo "message<<${delimiter}" >> "${GITHUB_OUTPUT}"
          git log -1 --pretty=%B | tail +3 | nix run github:iff/flakers >> "${GITHUB_OUTPUT}"
          echo "${delimiter}" >> "${GITHUB_OUTPUT}"

      - run: nix develop -c -- scripts/refresh-readme.sh

      - uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
        with:
          branch: update
          title: Update
          body: "${{ steps.nix-flake-changelog.outputs.message }}"
